// ====================================================
// uiText.ts — ข้อความของหน้าทดลองเล่น (จัดทีม · โหลด) ภาษาอังกฤษ / ไทย
// ภาษาใช้ค่าเดียวกับจอดวล (i18n.ts · จำใน localStorage) — เปลี่ยนที่ไหนก็เปลี่ยนทั้งหน้า
// ====================================================

import { useEffect, useState } from 'react'
import type { Category, Role } from '@/lib/rangerClass'
import type { Row } from '@/lib/rangerConfig'
import { getLang, onLangChange, type Lang } from './i18n'

const T = {
  appTitle: ['RANGER ARENA', 'RANGER ARENA'],
  appSub: ['5v5 Turn-Based Battle', 'ดวลเทิร์นเบส 5v5'],
  myTeam: ['YOUR TEAM', 'ทีมของคุณ'],
  enemyTeam: ['ENEMY TEAM', 'ทีมศัตรู'],
  random: ['Random', 'สุ่ม'],
  clear: ['Clear', 'ล้าง'],
  start: ['START BATTLE', 'เริ่มดวล'],
  needBoth: ['Put at least 1 ranger in each team', 'ใส่เรนเจอร์อย่างน้อยทีมละ 1 ตัว'],
  loading: ['Loading rangers…', 'กำลังโหลดเรนเจอร์…'],
  loadFail: ['Loading failed', 'โหลดไม่สำเร็จ'],
  rangers: ['RANGERS', 'เรนเจอร์'],
  search: ['Search name…', 'ค้นหาชื่อ…'],
  all: ['All', 'ทั้งหมด'],
  element: ['Element', 'ธาตุ'],
  role: ['Role', 'ตำแหน่ง'],
  klass: ['Type', 'ชนิด'],
  sort: ['Sort', 'เรียง'],
  sortGrade: ['★ Grade', '★ ระดับ'],
  sortName: ['Name', 'ชื่อ'],
  sortHp: ['HP', 'HP'],
  sortAtk: ['ATK', 'ATK'],
  sortSpd: ['Speed', 'Speed'],
  noMatch: ['No rangers match these filters', 'ไม่มีเรนเจอร์ที่ตรงกับตัวกรอง'],
  noRangers: ['No rangers available yet', 'ยังไม่มีเรนเจอร์ที่พร้อมเล่น'],
  empty: ['Empty', 'ว่าง'],
  front: ['FRONT', 'แถวหน้า'],
  back: ['BACK', 'แถวหลัง'],
  info: ['Details', 'ข้อมูล'],
  remove: ['Remove', 'ลบ'],
  change: ['Change', 'เปลี่ยน'],
  current: ['IN SLOT', 'ช่องนี้'],
  close: ['Close', 'ปิด'],
  help: ['How to play', 'วิธีเล่น'],
  reserve: ['SPECIAL ROW', 'แถวพิเศษ'],
  reserveHint: ['Not on the field · summon on your turn to cast a skill', 'ไม่ลงสนาม · ถึงตาเราอัญเชิญมาร่ายสกิลได้'],
  howReserve: ['Special row (summon)', 'แถวพิเศษ (อัญเชิญ)'],
  reserveText: [
    'Each team can add up to 2 rangers to the special row. They stay off the field. On any of your turns you may summon one of them instead of acting (keys A S / D F) to cast its Skill 1 or 2 — it costs that skill\'s Cost, uses its own raw stats (no row bonus, no buffs), then leaves and rests for 8 of your team\'s turns.',
    'ใส่เรนเจอร์แถวพิเศษได้ทีมละ 2 ตัว ไม่ลงสนาม · ถึงตาใครในทีมก็ได้ เลือกอัญเชิญแทนการใช้ท่าของตัวเอง (ปุ่ม A S / D F) มาร่ายสกิล 1 หรือ 2 ของตัวนั้น · เสีย Cost ตามสกิล · ใช้ค่าพลังดิบ (ไม่ได้โบนัสแถว ไม่ได้บัฟ) แล้วกลับไปพัก 8 เทิร์นของทีม',
  ],
  rotate: ['Rotate your phone to landscape to play', 'หมุนโทรศัพท์เป็นแนวนอนเพื่อเล่น'],
  inAppWarn: ['This in-app browser cannot play full screen — open the game in Chrome for the best experience', 'เบราว์เซอร์ในแอปนี้เล่นแบบเต็มจอไม่ได้ — เปิดเกมใน Chrome จะเล่นได้เต็มจอ'],
  inAppHowTo: ['Tap ⋯ (top-right) and choose "Open in browser" / "Open in Safari" to play full screen', 'แตะ ⋯ มุมขวาบน แล้วเลือก "เปิดในเบราว์เซอร์" / "Open in Safari" เพื่อเล่นแบบเต็มจอ'],
  openBrowser: ['Open in Chrome', 'เปิดใน Chrome'],
  tapFullscreen: ['Tap to continue in full screen', 'แตะเพื่อเล่นต่อแบบเต็มจอ'],
  pickTitle: ['Choose a ranger — {team} · {row}', 'เลือกเรนเจอร์ — {team} · {row}'],
  inMine: ['YOURS', 'ทีมคุณ'],
  inEnemy: ['ENEMY', 'ศัตรู'],
  teamFull: ['Team is full', 'ทีมเต็มแล้ว'],
  pickHint: ['Click an empty slot to choose a ranger · click a card for details · drag cards into slots or between slots', 'คลิกช่องว่างเพื่อเลือกเรนเจอร์ · คลิกการ์ดเพื่อดูข้อมูล · ลากการ์ดใส่ช่อง หรือลากสลับตำแหน่ง'],
  placing: ['Selected: {name} — click an empty slot to place', 'เลือก {name} อยู่ — คลิกช่องว่างเพื่อวาง'],
  detailEmpty: ['Select a ranger to see stats and skills', 'เลือกเรนเจอร์เพื่อดูค่าพลังและสกิล'],
  stats: ['STATS', 'ค่าพลัง'],
  skills: ['SKILLS', 'สกิล'],
  ability: ['ROLE ABILITY', 'ความสามารถตำแหน่ง'],
  normalAttack: ['Attack', 'ตีธรรมดา'],
  normalAttackText: ['100% ATK · gains +1 Cost', '100% ATK · ได้ Cost +1'],
  cost: ['Cost', 'Cost'],
  goodFit: ['fits this row', 'เข้ากับแถวนี้'],
  howTo: ['HOW TO PLAY', 'วิธีเล่น'],
  howRows: ['Row bonuses', 'โบนัสตามแถว'],
  howRoles: ['Role abilities', 'ความสามารถของแต่ละตำแหน่ง'],
  howControls: ['Controls', 'การควบคุม'],
  controlsText: [
    'On your turn pick Attack / Skill 1 / Skill 2 (keys Z / X / C), then click a target. Press the same key again to auto-aim when there is only one choice. AUTO plays for you; the speed button cycles x1 → x2 → x4.',
    'ถึงตาคุณ: เลือกตีธรรมดา / สกิล 1 / สกิล 2 (ปุ่ม Z / X / C) แล้วคลิกเป้า · กดปุ่มเดิมซ้ำ = เล็งให้เองถ้ามีเป้าเดียว · AUTO = ให้เล่นเอง · ปุ่มความเร็วกดวน x1 → x2 → x4',
  ],
  energyText: [
    'Skills cost team energy (Cost). Normal attacks give +1 Cost. Win by defeating the whole enemy team — after 80 turns the team with more HP % wins.',
    'สกิลใช้พลังงานทีม (Cost) · ตีธรรมดาได้ Cost +1 · ชนะเมื่อล้มศัตรูหมดทีม — ครบ 80 เทิร์น ทีมที่เหลือเลือด % มากกว่าชนะ',
  ],
  statHp: ['HP', 'HP'], statAtk: ['ATK', 'ATK'], statDef: ['DEF', 'DEF'], statSpd: ['Speed', 'Speed'],
  statCrit: ['Crit', 'คริ'], statCritDmg: ['Crit DMG', 'คริดาเมจ'], statEvade: ['Evade', 'หลบ'], statHit: ['Hit', 'แม่นยำ'],
  statSkillEvade: ['Skill Evade', 'หลบสกิล'], statSkillHit: ['Skill Hit', 'แม่นสกิล'], statSkillRes: ['Resist', 'ต้านสกิล'],
  statSkillDmgRes: ['Skill DMG Res', 'ต้านดาเมจสกิล'],

  // ── หน้าหลัก (Lobby) ──
  lobby: ['LOBBY', 'หน้าหลัก'],
  reserveRow: ['RESERVE', 'แถวพิเศษ'],
  lvShort: ['Lv.', 'Lv.'],
  power: ['POWER', 'พลังรวม'],
  myTeamShort: ['MY TEAM', 'ทีมของฉัน'],
  editTeam: ['Edit team', 'แก้ไขทีม'],
  noTeamYet: ['No team set yet', 'ยังไม่ได้จัดทีม'],
  modes: ['GAME MODES', 'โหมดเล่น'],
  soon: ['Soon', 'เร็วๆ นี้'],
  ready: ['Ready', 'พร้อมเล่น'],
  modePractice: ['Practice Duel', 'ดวลฝึกซ้อม'],
  modePracticeSub: ['Build both teams and fight right away', 'จัดทีมสองฝั่งแล้วลงดวลได้เลย'],
  modeCampaign: ['Campaign', 'โหมดเนื้อเรื่อง'],
  modeCampaignSub: ['Clear stages, earn gold and gear', 'ตะลุยด่าน เก็บเงินและไอเทม'],
  modeArena: ['Arena', 'สนามประลอง'],
  modeArenaSub: ['Fight other players’ defence teams', 'ท้าทีมตั้งรับของผู้เล่นคนอื่น'],
  modeBoss: ['Boss Raid', 'ล่าบอส'],
  modeBossSub: ['Team up against a huge boss', 'รุมบอสตัวใหญ่กับเพื่อนร่วมทีม'],
  modeDaily: ['Daily Quests', 'ภารกิจประจำวัน'],
  modeDailySub: ['Small missions, daily rewards', 'ภารกิจเล็กๆ รับรางวัลทุกวัน'],
  navHeroes: ['Heroes', 'ฮีโร่'],
  navTeam: ['Team', 'ทีม'],
  navBag: ['Bag', 'กระเป๋า'],
  navShop: ['Shop', 'ร้านค้า'],
  navGacha: ['Summon', 'กาชา'],
  navMail: ['Mail', 'กล่องข้อความ'],
  navSettings: ['Settings', 'ตั้งค่า'],
  battleNow: ['BATTLE', 'ลงดวล'],
  panelHeroesSub: ['Level up, evolve and inspect every hero you own', 'อัปเลเวล วิวัฒนาการ และดูข้อมูลฮีโร่ทุกตัวที่มี'],
  panelBagSub: ['Materials, gear and consumables', 'วัตถุดิบ อุปกรณ์สวมใส่ และของใช้'],
  panelShopSub: ['Daily deals, packs and currency exchange', 'ของลดประจำวัน แพ็กเกจ และแลกเปลี่ยนสกุลเงิน'],
  panelGachaSub: ['Summon new heroes with gems or tickets', 'สุ่มฮีโร่ตัวใหม่ด้วยเพชรหรือตั๋ว'],
  panelMailSub: ['Rewards and news from the team', 'ของรางวัลและข่าวจากทีมงาน'],
  wip: ['Under construction', 'กำลังพัฒนา'],
  wipNote: ['The layout is ready — the system will be filled in later.', 'วางโครงหน้าไว้แล้ว เดี๋ยวค่อยใส่ระบบจริงทีหลัง'],
  theme: ['Theme', 'ธีม'],
  themeNeon: ['Neon', 'นีออน'],
  themePixel: ['Pixel', 'พิกเซล'],
  language: ['Language', 'ภาษา'],
  resetProfile: ['Reset demo data', 'ล้างข้อมูลทดลอง'],
  more: ['More', 'เพิ่มเติม'],
  // ── หน้าฮีโร่ ──
  tabInfo: ['Info', 'ข้อมูล'],
  tabSkills: ['Skills', 'สกิล'],
  tabUpgrade: ['Upgrade', 'อัพเกรด'],
  tabLimit: ['Limit Break', 'ข้ามขีดจำกัด'],
  powAtk: ['Attack', 'พลังโจมตี'],
  powHp: ['Health', 'พลังชีวิต'],
  powDef: ['Defence', 'พลังป้องกัน'],
  powSpd: ['Attack Speed', 'ความเร็วโจมตี'],
  powCrit: ['Crit Rate', 'อัตราคริติคอล'],
  gearWeapon: ['Weapon', 'อาวุธ'],
  gearArmor: ['Armor', 'เกราะ'],
  gearAcc: ['Accessory', 'เครื่องประดับ'],
  gearTome: ['Tome', 'คัมภีร์'],
  filter: ['Filter', 'ฟิลเตอร์'],
  levelLabel: ['Level', 'เลเวล'],
  ownedHeroes: ['Heroes', 'ฮีโร่ทั้งหมด'],
  panelUpgradeSub: ['Spend gold and materials to raise stats', 'ใช้เงินและวัตถุดิบเพิ่มค่าพลัง'],
  panelLimitSub: ['Break the level cap with duplicate heroes', 'ใช้ตัวซ้ำปลดเพดานเลเวล'],
  levelSoon: ['Level system is not in yet', 'ระบบเลเวลยังไม่เปิด'],
  skillAttack: ['Attack skill', 'สกิลโจมตี'],
  skillBuff: ['Buff skill', 'สกิลบัฟ'],
  // ── หน้ากาชา ──
  bannerStd: ['Standard Summon', 'ตู้เรนเจอร์ถาวร'],
  bannerStdSub: ['All rangers, always available', 'เรนเจอร์ทุกตัว เปิดตลอดเวลา'],
  bannerEvent: ['Event Summon', 'ตู้เรนเจอร์อีเวนต์'],
  bannerEventSub: ['Featured rangers, limited time', 'เรนเจอร์พิเศษ เปิดช่วงเวลาจำกัด'],
  bannerGear: ['Equipment Summon', 'ตู้อุปกรณ์'],
  bannerGearSub: ['Weapons, armor and more', 'อาวุธ เกราะ และอื่นๆ'],
  gearSoon: ['Equipment system is not in yet', 'ระบบอุปกรณ์ยังไม่เปิด'],
  pull1: ['Summon ×1', 'สุ่ม 1 ครั้ง'],
  pull10: ['Summon ×10', 'สุ่ม 10 ครั้ง'],
  pickUp: ['PICK UP', 'อัตราพิเศษ'],
  rates: ['Rates', 'อัตราออก'],
  guarantee10: ['×10 guarantees Rare or better', 'สุ่ม 10 ครั้ง การันตีระดับหายากขึ้นไป'],
  notEnoughGem: ['Not enough gems', 'เพชรไม่พอ'],
  tapPack: ['Tap the pack to open', 'แตะซองเพื่อเปิด'],
  tapCard: ['Tap a card to reveal', 'แตะการ์ดเพื่อเปิด'],
  skipAll: ['Skip', 'ข้ามทั้งหมด'],
  done: ['Done', 'เสร็จสิ้น'],
  rarityCommon: ['Common', 'ธรรมดา'],
  rarityRare: ['Rare', 'หายาก'],
  rarityEpic: ['Epic', 'พิเศษ'],
  rarityLegend: ['Legendary', 'ตำนาน'],
  newTag: ['NEW', 'ใหม่'],
  freeGem: ['Prototype: gems are not charged yet', 'โหมดทดลอง: ยังไม่หักเพชร'],
  navProfile: ['Profile', 'โปรไฟล์'],
  navEvents: ['Events', 'กิจกรรม'],
  navQuests: ['Quests', 'เควส'],
  navPass: ['Season Pass', 'ซีซั่นพาส'],
  navNotice: ['Notice', 'ประกาศ'],
  navGuild: ['Guild', 'กิลด์'],
  navRank: ['Ranking', 'อันดับ'],
  navCodex: ['Codex', 'สารานุกรม'],
  navAchieve: ['Achievements', 'ความสำเร็จ'],
  panelRankSub: ['Season leaderboards', 'ตารางอันดับประจำซีซั่น'],
  panelCodexSub: ['Every hero, item and enemy you have met', 'รวมฮีโร่ ไอเทม และศัตรูที่เคยเจอ'],
  panelAchieveSub: ['Milestones and their rewards', 'เป้าหมายสะสมและของรางวัล'],
  navForge: ['Upgrade', 'อัพอาวุธ'],
  navFriends: ['Friends', 'เพื่อน'],
  addFriend: ['Add friend', 'เพิ่มเพื่อน'],
  online: ['online', 'ออนไลน์'],
  play: ['PLAY', 'เล่น'],
  leader: ['Leader', 'หัวหน้าทีม'],
  modeStory: ['Main Story', 'เนื้อเรื่องหลัก'],
  modeStorySub: ['Clear the story stage by stage', 'ไล่เก็บด่านตามเนื้อเรื่อง'],
  modeSide: ['Side Story', 'เนื้อเรื่องพิเศษ'],
  modeSideSub: ['Limited chapters and events', 'ตอนพิเศษและกิจกรรมตามช่วงเวลา'],
  modeDungeon: ['Dungeon', 'ดันเจี้ยน'],
  modeDungeonSub: ['Farm gold and upgrade materials', 'เก็บเงินและวัตถุดิบอัปเกรด'],
  modeTower: ['Tower', 'หอคอย'],
  modeTowerSub: ['Climb floor by floor, no healing between', 'ไต่ทีละชั้น เลือดไม่ฟื้นระหว่างชั้น'],
  panelEventsSub: ['Limited-time events and rewards', 'กิจกรรมช่วงเวลาและของรางวัล'],
  panelQuestsSub: ['Daily, weekly and achievement quests', 'เควสรายวัน รายสัปดาห์ และความสำเร็จ'],
  panelPassSub: ['Season rewards track', 'เส้นทางรางวัลประจำซีซั่น'],
  panelNoticeSub: ['Patch notes and announcements', 'ประกาศและบันทึกการอัปเดต'],
  panelGuildSub: ['Guild hall, members and guild war', 'บ้านกิลด์ สมาชิก และสงครามกิลด์'],
  panelForgeSub: ['Upgrade and enhance gear', 'อัปเกรดและตีบวกอุปกรณ์'],
  panelFriendsSub: ['Friend list, support heroes and gifts', 'รายชื่อเพื่อน ฮีโร่ช่วยรบ และของขวัญ'],
} as const satisfies Record<string, readonly [string, string]>

export type UiKey = keyof typeof T
const ZH: Record<UiKey, string> = {
  "appTitle": "LINE Rangers 競技場",
  "appSub": "5v5 回合制對戰",
  "myTeam": "我方隊伍",
  "enemyTeam": "敵方隊伍",
  "random": "隨機",
  "clear": "清除",
  "start": "開始戰鬥",
  "needBoth": "雙方隊伍都至少要放入 1 名 Ranger",
  "loading": "正在載入 Rangers…",
  "loadFail": "載入失敗",
  "rangers": "RANGERS",
  "search": "搜尋名稱…",
  "all": "全部",
  "element": "屬性",
  "role": "定位",
  "klass": "類型",
  "sort": "排序",
  "sortGrade": "★ 星等",
  "sortName": "名稱",
  "sortHp": "HP",
  "sortAtk": "ATK",
  "sortSpd": "攻擊速度",
  "noMatch": "沒有符合篩選條件的 Rangers",
  "noRangers": "目前沒有可用的 Rangers",
  "empty": "空",
  "front": "前排",
  "back": "後排",
  "info": "詳細資料",
  "remove": "移除",
  "change": "更換",
  "current": "目前欄位",
  "close": "關閉",
  "help": "遊玩方式",
  "reserve": "特殊列",
  "reserveHint": "不上場 · 輪到我方時可召喚並施放技能",
  "howReserve": "特殊列（召喚）",
  "reserveText": "每支隊伍最多可在特殊列放入 2 名 Ranger，他們不會直接上場。輪到我方任一 Ranger 行動時，可改為召喚其中一名（快捷鍵 A/S 或 D/F）施放技能 1 或技能 2；會消耗該技能的 Cost，並使用自身原始能力值（不套用排位加成與增益）。施放後離場，並進入我方 8 個回合的休息時間。",
  "rotate": "請將手機旋轉為橫向以進行遊戲",
  "inAppWarn": "此 App 內建瀏覽器無法全螢幕遊玩，建議改用 Chrome 開啟以獲得最佳體驗",
  "inAppHowTo": "點擊右上角 ⋯，選擇「在瀏覽器中開啟」或「在 Safari 中開啟」即可全螢幕遊玩",
  "openBrowser": "在 Chrome 開啟",
  "tapFullscreen": "點擊以全螢幕繼續",
  "pickTitle": "選擇 Ranger — {team} · {row}",
  "inMine": "我方",
  "inEnemy": "敵方",
  "teamFull": "隊伍已滿",
  "pickHint": "點擊空欄位選擇 Ranger · 點擊卡片查看詳細資料 · 可拖曳卡片放入欄位或交換位置",
  "placing": "已選擇：{name} — 點擊空欄位放置",
  "detailEmpty": "選擇 Ranger 以查看能力值與技能",
  "stats": "能力值",
  "skills": "技能",
  "ability": "定位能力",
  "normalAttack": "普通攻擊",
  "normalAttackText": "100% ATK · Cost +1",
  "cost": "Cost",
  "goodFit": "適合此排",
  "howTo": "遊玩方式",
  "howRows": "排位加成",
  "howRoles": "定位能力",
  "howControls": "操作方式",
  "controlsText": "輪到你時選擇普通攻擊／技能 1／技能 2（快捷鍵 Z／X／C），再點擊目標。若只有一個可選目標，再按一次相同快捷鍵即可自動瞄準。AUTO 會自動進行戰鬥；速度按鈕依序切換 x1 → x2 → x4。",
  "energyText": "技能會消耗隊伍能量（Cost），普通攻擊可獲得 +1 Cost。擊倒敵方全隊即可獲勝；若達到 80 回合上限，剩餘 HP 百分比較高的一方獲勝。",
  "statHp": "HP",
  "statAtk": "ATK",
  "statDef": "DEF",
  "statSpd": "攻擊速度",
  "statCrit": "暴擊率",
  "statCritDmg": "暴擊傷害",
  "statEvade": "閃避率",
  "statHit": "命中率",
  "statSkillEvade": "技能閃避率",
  "statSkillHit": "技能命中率",
  "statSkillRes": "技能抵抗",
  "statSkillDmgRes": "技能傷害抵抗",
  "lobby": "大廳",
  "reserveRow": "特殊列",
  "lvShort": "Lv.",
  "power": "總戰力",
  "myTeamShort": "我的隊伍",
  "editTeam": "編輯隊伍",
  "noTeamYet": "尚未配置隊伍",
  "modes": "遊戲模式",
  "soon": "即將推出",
  "ready": "可遊玩",
  "modePractice": "練習對戰",
  "modePracticeSub": "配置雙方隊伍後立即進行對戰",
  "modeCampaign": "冒險模式",
  "modeCampaignSub": "挑戰關卡並取得金幣與裝備",
  "modeArena": "競技場",
  "modeArenaSub": "挑戰其他玩家的防守隊伍",
  "modeBoss": "Boss 討伐",
  "modeBossSub": "組隊挑戰強大的 Boss",
  "modeDaily": "每日任務",
  "modeDailySub": "完成每日小任務並領取獎勵",
  "navHeroes": "Rangers",
  "navTeam": "隊伍",
  "navBag": "背包",
  "navShop": "商店",
  "navGacha": "召喚",
  "navMail": "信箱",
  "navSettings": "設定",
  "battleNow": "戰鬥",
  "panelHeroesSub": "升級、進化並查看你擁有的 Rangers",
  "panelBagSub": "素材、裝備與消耗道具",
  "panelShopSub": "每日特價、禮包與貨幣兌換",
  "panelGachaSub": "使用寶石或票券召喚新的 Rangers",
  "panelMailSub": "領取獎勵並查看營運公告",
  "wip": "開發中",
  "wipNote": "頁面版型已完成，功能將於後續加入。",
  "theme": "主題",
  "themeNeon": "霓虹",
  "themePixel": "像素",
  "language": "語言",
  "resetProfile": "重設測試資料",
  "more": "更多",
  "tabInfo": "資訊",
  "tabSkills": "技能",
  "tabUpgrade": "強化",
  "tabLimit": "突破",
  "powAtk": "攻擊力",
  "powHp": "體力",
  "powDef": "防禦力",
  "powSpd": "攻擊速度",
  "powCrit": "暴擊率",
  "gearWeapon": "武器",
  "gearArmor": "防具",
  "gearAcc": "飾品",
  "gearTome": "魔法書",
  "filter": "篩選",
  "levelLabel": "等級",
  "ownedHeroes": "Rangers",
  "panelUpgradeSub": "消耗金幣與素材提升能力值",
  "panelLimitSub": "使用重複 Ranger 突破等級上限",
  "levelSoon": "等級系統尚未開放",
  "skillAttack": "攻擊技能",
  "skillBuff": "輔助技能",
  "bannerStd": "一般召喚",
  "bannerStdSub": "所有 Rangers，常駐開放",
  "bannerEvent": "活動召喚",
  "bannerEventSub": "精選 Rangers，期間限定",
  "bannerGear": "裝備召喚",
  "bannerGearSub": "武器、防具與其他裝備",
  "gearSoon": "裝備系統尚未開放",
  "pull1": "召喚 ×1",
  "pull10": "召喚 ×10",
  "pickUp": "機率提升",
  "rates": "提供機率",
  "guarantee10": "10 連召喚保證稀有以上",
  "notEnoughGem": "寶石不足",
  "tapPack": "點擊卡包開啟",
  "tapCard": "點擊卡片揭曉",
  "skipAll": "全部略過",
  "done": "完成",
  "rarityCommon": "普通",
  "rarityRare": "稀有",
  "rarityEpic": "史詩",
  "rarityLegend": "傳說",
  "newTag": "新",
  "freeGem": "測試版：目前尚不扣除寶石",
  "navProfile": "個人資料",
  "navEvents": "活動",
  "navQuests": "任務",
  "navPass": "賽季通行證",
  "navNotice": "公告",
  "navGuild": "公會",
  "navRank": "排行榜",
  "navCodex": "圖鑑",
  "navAchieve": "成就",
  "panelRankSub": "賽季排行榜",
  "panelCodexSub": "收錄你曾遇過的 Ranger、道具與敵人",
  "panelAchieveSub": "累積成就與對應獎勵",
  "navForge": "裝備強化",
  "navFriends": "好友",
  "addFriend": "新增好友",
  "online": "上線",
  "play": "遊玩",
  "leader": "隊長",
  "modeStory": "主線故事",
  "modeStorySub": "依序攻略主線關卡",
  "modeSide": "支線故事",
  "modeSideSub": "期間限定章節與活動",
  "modeDungeon": "地下城",
  "modeDungeonSub": "取得金幣與強化素材",
  "modeTower": "高塔",
  "modeTowerSub": "逐層挑戰，層與層之間不恢復 HP",
  "panelEventsSub": "期間限定活動與獎勵",
  "panelQuestsSub": "每日、每週與成就任務",
  "panelPassSub": "賽季獎勵進度",
  "panelNoticeSub": "更新資訊與公告",
  "panelGuildSub": "公會大廳、成員與公會戰",
  "panelForgeSub": "強化並升級裝備",
  "panelFriendsSub": "好友清單、支援 Ranger 與贈禮"
}

export const ui = (k: UiKey, vars?: Record<string, string>): string => {
  const lang = getLang()
  let s: string = lang === 'zh-TW' ? ZH[k] : T[k][lang === 'th' ? 1 : 0]
  if (vars) for (const [key, v] of Object.entries(vars)) s = s.replace(`{${key}}`, v)
  return s
}

/** ภาษาปัจจุบัน — คอมโพเนนต์ที่เรียกจะรีเรนเดอร์เมื่อเปลี่ยนภาษา */
export function useLang(): Lang {
  const [l, setL] = useState<Lang>(getLang())
  useEffect(() => onLangChange(setL), [])
  return l
}

const pick = (pair: readonly [string, string], zhTw?: string) =>
  getLang() === 'zh-TW' ? (zhTw ?? pair[0]) : pair[getLang() === 'th' ? 1 : 0]

/** ความสามารถประจำตำแหน่ง (ตรงกับค่าจริงใน lib/roleTraits.ts) */
const TRAIT: Record<Role, { label: readonly [string, string]; text: readonly [string, string] }> = {
  tank: { label: ['Wall', 'กำแพง'], text: ['Takes 15% less damage · enemies tend to target it first', 'รับดาเมจลดลง 15% · ศัตรูมักเล็งตัวนี้ก่อน'] },
  fighter: { label: ['Lifesteal', 'ดูดเลือด'], text: ['Heals 15% of the damage it deals', 'ฟื้นเลือด 15% ของดาเมจที่ทำได้'] },
  shooter: { label: ['Sharpshooter', 'ยิงแม่น'], text: ['Normal attacks deal 25% more', 'ตีปกติแรงขึ้น 25%'] },
  assassin: { label: ['Assassinate', 'ลอบสังหาร'], text: ['Can hit any enemy (skips the front row) · +30% vs targets below half HP', 'ตีข้ามแถวได้ทุกตัว · ตีเป้าที่เลือดต่ำกว่าครึ่ง +30%'] },
  mage: { label: ['Arcane Power', 'เวทรุนแรง'], text: ['Skill damage +20%', 'ดาเมจสกิลแรงขึ้น 20%'] },
  support: { label: ['Caretaker', 'สายเลี้ยง'], text: ['Heals and shields +25% · team starts with +1 Cost', 'ฮีล/โล่ที่ให้เพิ่ม 25% · ทีมเริ่มเกมพลังงาน +1'] },
}
const TRAIT_ZH: Record<Role, { label: string; text: string }> = {
  tank: { label: '壁壘', text: '受到傷害 −15% · 敵人會優先鎖定' },
  fighter: { label: '吸血', text: '造成傷害的 15% 轉為恢復' },
  shooter: { label: '神射手', text: '普通攻擊傷害 +25%' },
  assassin: { label: '暗殺', text: '可攻擊任意敵人（無視前排）· 對 HP 低於 50% 的目標傷害 +30%' },
  mage: { label: '魔力強化', text: '技能傷害 +20%' },
  support: { label: '支援', text: '治療與護盾 +25% · 隊伍起始 Cost +1' },
}
export const traitLabel = (r: Role): string => getLang() === 'zh-TW' ? TRAIT_ZH[r].label : pick(TRAIT[r].label)
export const traitText = (r: Role): string => getLang() === 'zh-TW' ? TRAIT_ZH[r].text : pick(TRAIT[r].text)

/** โบนัสแถว (ตรงกับ lib/formation.ts) */
export const rowBonusText = (row: Row): string =>
  row === 'front'
    ? pick(['DEF +30% · HP +15% — best for Tank / Fighter', 'DEF +30% · HP +15% — เหมาะกับแทงค์ / ไฟเตอร์'], 'DEF +30% · HP +15% — 適合坦克／戰士')
    : pick(['ATK +15% · Crit +8 — best for Shooter / Assassin / Mage / Support', 'ATK +15% · คริ +8 — เหมาะกับนักยิง / นักฆ่า / นักเวท / ซัพพอร์ต'], 'ATK +15% · 暴擊 +8 — 適合射手／刺客／法師／輔助')
export const rowBonusShort = (row: Row): string =>
  row === 'front' ? 'DEF +30% · HP +15%' : pick(['ATK +15% · Crit +8', 'ATK +15% · คริ +8'], 'ATK +15% · 暴擊 +8')

const CATEGORY: Record<Category, readonly [string, string]> = { str: ['STR', 'พลัง'], agi: ['AGI', 'ว่องไว'], int: ['INT', 'ไหวพริบ'] }
const CATEGORY_ZH: Record<Category, string> = { str: '力量型', agi: '敏捷型', int: '智慧型' }
export const categoryName = (cat: Category): string => getLang() === 'zh-TW' ? CATEGORY_ZH[cat] : pick(CATEGORY[cat])
